name: Capstone-Repose
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - contextily
  - flask
  - geopandas
  - huggingface_hub
  - ipykernel
  - jupyterlab
  - lightgbm
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pyarrow
  - pydantic
  - pyyaml
  - scikit-learn
  - seaborn
  - shapely
  - tqdm
  - pip:
      - modelscope
      - peft
      - rouge
      - sentence-transformers
      - transformers
      - vllm
