adapter_name_or_path: saves/Qwen3-4B-Instruct-2507/lora/train_2026-05-19-19-00-50
bf16: true
cutoff_len: 2048
dataset: dpo_data
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
eval_steps: 50
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-07
logging_steps: 5
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: ../Qwen3-4B
num_train_epochs: 2.0
optim: adamw_8bit
output_dir: ../checkpoints/train_2026-05-23-20-15-30
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
plot_loss: true
pref_beta: 0.7
pref_ftx: 0.1
pref_loss: sigmoid
preprocessing_num_workers: 16
report_to: none
save_steps: 50
stage: dpo
template: qwen3_nothink
trust_remote_code: true
use_swanlab: false
val_size: 0.1
warmup_steps: 20
